# Generated by Django 4.2.27 on 2026-01-22 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='answer',
            name='game_answer_question_player_unique',
        ),
        migrations.RemoveConstraint(
            model_name='player',
            name='game_player_room_name_unique',
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('question', 'player')},
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('room', 'name')},
        ),
    ]
