# Generated by Django 4.2.27 on 2026-01-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_answer_game_answer_question_player_unique_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandaloneRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('user_name', models.CharField(max_length=100)),
                ('question_type', models.CharField(blank=True, max_length=10, null=True)),
                ('current_question', models.TextField(blank=True, null=True)),
                ('question_source', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
