# Generated by Django 4.2.27 on 2026-01-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_standalonerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='standalonerequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Admin Approval'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
    ]
